name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish assets for ${{ matrix.job.os }}/${{ matrix.job.arch }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        job:
          - { os: darwin, arch: amd64 }
          - { os: linux, arch: amd64 }
          - { os: windows, arch: amd64 }

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          GOOS: ${{ matrix.job.os }}
          GOARCH: ${{ matrix.job.arch }}
        run: go build

      - name: Package
        env:
          GOOS: ${{ matrix.job.os }}
          GOARCH: ${{ matrix.job.arch }}
          PROJECT_NAME: msgenctl
        shell: bash
        run: .github/scripts/package.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: msgenctl-*-${{ matrix.job.os }}-${{ matrix.job.arch }}.*
